import LayoutProvider from '@/components/layout-provider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import { getUser } from '@/lib/session';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Air Care',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUser();
  return (
    <html lang='en'>
      <body className={inter.className}>
        <LayoutProvider user={user}>{children}</LayoutProvider>
        <Toaster />
      </body>
    </html>
  );
}
